#!/bin/bash

SRC=$(echo "${PWD}" | sed -e 's|^/cygdrive/\(.\)/|\1:/|g')
SRC="${SRC}/source"

echo "Mapping ${SRC} to /source"
docker run --rm -v ${SRC}:/source drunner/builddrunner:xplatform

OUTPUT=source/output/drunner-install

[ -f ${OUTPUT} ] || { echo "Build Failed." ; exit 1 ; }

cp ${OUTPUT} .

