#!/bin/bash

if [[ $EUID -eq 0 ]]; then
   echo "This script should be run as a normal user, not root." 1>&2
   exit 1
fi

echo "Updating dRunner..."
docker run --rm -v "/usr/local/bin:/ulb" "drunner/drunner_utils" bash -c \


echo "dRunner updated."
echo "Updating dRunner setup..."
drunner initialise

echo "dRunner setup updated."
